language: python
python:
  - "pypy"
  - "2.7"
  - "pypy3"
  - "3.3"
  - "3.4"
  - "3.5.0b3"

# Use fast travis build infrastructure explicitly
sudo: false

# Installation installs dependencies
install: python setup.py install

script: python tests/run_tox.py
