language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy3

# Use fast travis build infrastructure explicitly
dist: trusty
sudo: false

# Installation installs dependencies
install:
  - pip install -r requirements.txt

script: python -E -Wall -tt -bb -m pytest tests
